#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other shells available, try using one of them.
#
#   (2) The returned exit code is expected to be the exit code of the last
#       command executed in the script. Exit statuses are not abstractions
#       like POSIX shells. If you try to call "exit 4" in a POSIX shell script,
#       "exit /b 4" will be accepted to give an exit code of 4 in CMD.exe
#
#   POSIX is a property of the Single UNIX Specification (SUS) pronounced 'single unix spec'.
#   Applications qualified as POSIX::Handler conform to the Single UNIX Specification.
#
#   Bugs/issues/suggestions can be reported at https://github.com/gradle/gradle/issues/HOME/
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a softlink
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls -ld "$PRG"
    link=`expr "$PRG" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != maximum.
MAX_FD="maximum"

warn ( ) {
    echo "$*" >&2
}

die ( ) {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
pw=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVACMD="$JAVA_HOME/bin/java"
    else
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
    command -v java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

if [ ! -x "$JAVACMD" ] ; then
    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
fi

# traverses directory structure from process work directory to filesystem root
# try to find a FILE named $1 starting from directory $2
find_file_arg() {
    local pattern=$(echo "$1" | sed "s/ /[[:space:]]/g")
    find "$2" -maxdepth 1 -type f | grep -E "$pattern" | head -n 1
}

# traverses directory structure from process work directory to filesystem root
# try to find a FILE named $1 starting from directory $2
find_file_arg() {
    local pattern=$(echo "$1" | sed "s/ /[[:space:]]/g")
    find "$2" -maxdepth 1 -type f | grep -E "$pattern" | head -n 1
}

# Initialize classpath too! We save it in a variable, so we can use it in a shell subprocess as there is a risk
# the user input will be overwritten again.
export CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# By default we should be using the Gradle daemon, so we will look for them first.
if ! "$JAVACMD" -version > /dev/null 2>&1; then
    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
fi

JVM_OPTS=($DEFAULT_JVM_OPTS "$JAVA_OPTS" "$GRADLE_OPTS")
exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
